# The format of this file is based on GNU_Make_Makefile_templates
# https://github.com/Vdragon/GNU_Make_Makefile_templates
# 變數
# Variables
NAME_PROJECT = "NAME_PROJECT undefined"
NAME_TARGET = "NAME_TARGET undefined"
NAME_MODULE = "NAME_MODULE undefined"

POSTFIX_TYPE_SOURCE_CODE_C = c
POSTFIX_TYPE_SOURCE_CODE_CPP = cpp
POSTFIX_TYPE_HEADER_C = h
POSTFIX_TYPE_HEADER_CPP = hpp
POSTFIX_TYPE_OBJECT_CODE_LINUX = o
POSTFIX_TYPE_OBJECT_CODE_DOS_WINDOWS = obj
POSTFIX_TYPE_OBJECT_CODE = ${POSTFIX_TYPE_OBJECT_CODE_LINUX}
POSTFIX_TYPE_EXECUTABLE = exe

COMPILER_GCC = gcc
COMPILER_GPP = g++
COMPILER_C = ${COMPILER_GCC}
COMPILER_CPP = ${COMPILER_GPP}
LINKER_GNU = ld
LINKER = ${LINKER_GNU}
REMOVER_WINDOWS = del
REMOVER_LINUX = rm
REMOVER = ${REMOVER_LINUX}
ARCHIVER_LIBRARY_GNU_AR = ar

DIR_SOURCE_CODE = Source_code
DIR_OBJECT_CODE = Object_code
DIR_BUILD = Build

OPTION_GCC_WITH_DEBUGGING_SYMBOLS = -g
OPTION_GPP_WITH_DEBUGGING_SYMBOLS = ${OPTION_GCC_WITH_DEBUGGING_SYMBOLS}
OPTION_GCC_ONLY_COMPILE = -c
OPTION_GPP_ONLY_COMPILE = ${OPTION_GCC_ONLY_COMPILE}
OPTION_GCC_OUTPUT = -o
OPTION_GPP_OUTPUT = ${OPTION_GCC_OUTPUT}
OPTION_MKDIR_CREATE_PARENT_AUTOMATICALLY = --parent
OPTION_REMOVER_LINUX_FORCE = --force
OPTION_GNU_LINKER_OUTPUT = -o
OPTION_GNU_LINKER_LINK_GLIBC = -lc
OPTION_GCC_WARNING_COMMON = -Wall
OPTION_GPP_WARNING_COMMON = ${OPTION_GCC_WARNING_COMMON}
OPTION_GCC_DEBUG_INFO_MORE = -g3
OPTION_GCC_DEBUG_INFO = ${OPTION_GCC_DEBUG_INFO_MORE}
OPTION_GCC_OPTIMIZE_NONE = -O0
OPTION_GCC_STANDARD_ANSI_C = -ansi
OPTION_GCC_STANDARD_C99 = -std=c99
OPTION_GCC_STANDARD = ${OPTION_GCC_STANDARD_ANSI_C}

COMMAND_GCC_ONLY_COMPILE = ${COMPILER_GCC} ${OPTION_GCC_ONLY_COMPILE} ${OPTION_GCC_WARNING_COMMON} ${OPTION_GCC_STANDARD_ANSI_C} ${OPTION_GCC_DEBUG_INFO} ${OPTION_GCC_OPTIMIZE_NONE}
COMMAND_GPP_ONLY_COMPILE = ${COMPILER_GPP} ${OPTION_GPP_ONLY_COMPILE} ${OPTION_GPP_WARNING_COMMON}
COMMAND_GNU_LINK = ${LINKER_GNU} ${OPTION_GNU_LINKER_LINK_GLIBC} ${OPTION_GNU_LINKER_OUTPUT} ${NAME_PROJECT}.${POSTFIX_TYPE_EXECUTABLE}
COMMAND_REMOVE_LINUX = ${REMOVER_LINUX} ${OPTION_REMOVER_LINUX_FORCE}

# 通用 Make 規則
# Generic Make rules
%.${POSTFIX_TYPE_OBJECT_CODE} : %.${POSTFIX_TYPE_SOURCE_CODE_C}
	${COMMAND_GCC_ONLY_COMPILE} $^
%.${POSTFIX_TYPE_OBJECT_CODE} : %.${POSTFIX_TYPE_SOURCE_CODE_CPP}
	${COMMAND_GPP_ONLY_COMPILE}  $^
%.${POSTFIX_TYPE_EXECUTABLE} : %.${POSTFIX_TYPE_OBJECT_CODE}
	${LINKER_GNU} ${OPTION_GNU_LINKER_LINK} ${OPTION_GNU_LINKER_OUTPUT} $@ $^
	
# 主要內容
# Main content
.PHONY : build
build : compile link

.PHONY : compile
compile : ${NAME_MODULE}.${POSTFIX_TYPE_OBJECT_CODE}

.PHONY : link
link : compile ${NAME_MODULE}.${POSTFIX_TYPE_EXECUTABLE}

.PHONY : clean
clean :
	${COMMAND_REMOVE_LINUX} *.${POSTFIX_TYPE_OBJECT_CODE} *.${POSTFIX_TYPE_EXECUTABLE}